name: 'Npm Version'
description: 'Workflow that updates npm version.'
inputs:
  version:
    description: 'Whether the version is major, minor, or patch.'
    required: true
  token:
    description: 'GitHub token for pushing changes.'
    required: true
  email_suffix:
    description: 'A random string at the end of the email of commits created by this action.'
    required: false
    default: ''
  on_finish:
    description: 'A node file to call when this is finished. The file must export a function which is called with github and octokit. The function can return a promise.'
    required: false
runs:
  using: 'node12'
  pre: 'install.js'
  main: 'index.js'
