name: 'Npm Version'
description: 'Workflow that updates npm version.'
inputs:
  version:
    description: 'Whether the version is major, minor, or patch.'
    required: true
  token:
    description: 'GitHub token for pushing changes.'
    required: true
  email_suffix:
    description: 'A random string at the end of the email of commits created by this action.'
    required: false
    default: ''
  on_finish:
    description: 'Trigger a manual workflow on finish. To specify the ref, separate with comma.'
    required: false
    default: ''
runs:
  using: 'node12'
  pre: 'install.js'
  main: 'index.js'
