name: 'Npm Version'
description: 'Workflow that updates npm version.'
inputs:
  version:
    description: 'Whether the version is major, minor, or patch.'
    required: true
  token:
    description: 'GitHub token for pushing changes.'
    required: true
  on_finish:
    description: 'Path to json file with on finish actions.'
    required: false
    default: ''
runs:
  using: 'node12'
  pre: '../install.js'
  main: 'index.js'
