name: 'Commit'
description: 'Commits files.'
inputs:
  files:
    description: 'The files to commit.'
    required: true
  message:
    description: 'The commit message.'
    required: true
  token:
    description: 'The GitHub token.'
    required: true
  branch:
    description: 'The branch to create the commit on.'
    required: false
  author:
    description: 'The name of the author.'
    required: false
  email:
    description: 'The email of the author.'
    required: false
runs:
  using: 'node12'
  pre: '../install.js'
  main: 'index.js'
